services:

  firefox:
    image: selenium/node-firefox
    depends_on:
      - hub
    shm_size: 2gb
    environment:
      - SE_NODE_MAX_SESSIONS=7
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - GRID_DEBUG=true
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH=4442
      - SE_EVENT_BUS_SUBSCRIBE=4443
