services:

  chrome:
    image: selenium/node-chrome
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 5900:5900
    depends_on:
      - hub
    # the standard setup proposes:
    #   shm_size: 2gb
    # but we use the /dev/shm mapping above
    environment:
      - SE_NODE_MAX_SESSIONS=7
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - GRID_DEBUG=true
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH=4442
      - SE_EVENT_BUS_SUBSCRIBE=4443
