
insert into trans_type (code, description)
values ('pa', 'The transaction is generated by a payment/receipt');

-- this fails if there are transactions with partially approved lines
-- further down, things will fail when approved or transdate are null
-- there are 8 'payment' rows in my real-life data set which don't have payment_links...

-- TODO!
-- check overpayment creation (payment_links.type = 0)
-- versus overpayment use (payment_links.type = 2)
-- versus (over)payment allocation (payment_links.type = 1)

create temporary table payment_transactions as
select
  nextval('transactions_id_seq') as id,
  payment.id as payment_id,
  'payment' as table_name,
  (select distinct approved
     from acc_trans ac
            join payment_links pl
                on ac.entry_id = pl.entry_id
    where pl.payment_id = payment.id) as approved,
  (select distinct transdate
     from acc_trans ac
            join payment_links pl
                on ac.entry_id = pl.entry_id
    where pl.payment_id = payment.id) as transdate,
  ('pay-' || reference) as reference,
  'this transaction was synthesized during payments-as-first-order-transactions migration' as description,
  'pa' as trans_type_code
  from payment
  where trans_id is null;


insert into transactions (
  id, table_name, approved, transdate, reference, description, trans_type_code
)
            overriding system value
select id, table_name, approved, transdate, reference, description, trans_type_code
  from payment_transactions
 where approved is not null
   and transdate is not null;

update payment p
   set trans_id = pt.id
       from payment_transactions pt
            join transactions txn
                 on txn.id = pt.id
 where p.id = pt.payment_id;


alter table acc_trans disable trigger acc_trans_prevent_closed;

update acc_trans ac
   set trans_id = pt.id
       from payment_transactions pt
            join payment_links pl
                 on pt.payment_id = pl.payment_id
 where pl.entry_id = ac.entry_id;

alter table acc_trans enable trigger acc_trans_prevent_closed;


drop table payment_transactions;

alter table payment
  drop constraint check_payment_trans_id_null;

delete from payment
 where trans_id is null;

alter table payment
  alter column trans_id set not null,
  add column account_id int references account(id);


-- this does not work for overpayments...
update payment p
   set account_id = (
     select distinct ac.chart_id
       from payment_links pl
              left join acc_trans ac
                  on pl.entry_id = ac.entry_id
              join account_link al
                  on ac.chart_id = al.account_id
      where al.description in ('AR_paid', 'AP_paid')
        and ac.amount_tc <> 0
        and p.id = pl.payment_id
   );

-- in my case, there were acc_trans rows which had an amount_tc = 0,
-- but there *was* a cash account with a non-zero amount_bc...
update payment p
   set account_id = (
     select distinct ac.chart_id
       from payment_links pl
              left join acc_trans ac
                  on pl.entry_id = ac.entry_id
              join account_link al
                  on ac.chart_id = al.account_id
      where al.description in ('AR_paid', 'AP_paid')
        and p.id = pl.payment_id
   )
 where p.account_id is null;

-- only works if there's a single overpayment account in the transaction...
update payment p
   set account_id = (
     select distinct ac.chart_id
       from payment_links pl
              left join acc_trans ac
                  on pl.entry_id = ac.entry_id
              join account_link al
                  on ac.chart_id = al.account_id
      where al.description in ('AR_overpayment', 'AP_overpayment')
        and p.id = pl.payment_id
   )
 where p.account_id is null;

-- can't be done until ... (when?)
alter table payment
  alter column account_id set not null;
